- .travis.yml
- Bootstrap/Bootstrap.xcodeproj/project.pbxproj
- Bootstrap/Bootstrap.xcodeproj/xcshareddata/xcschemes/Bootstrap.xcscheme
- Bootstrap/Bootstrap.xcworkspace/xcshareddata/Bootstrap.xccheckout
- Bootstrap/Gemfile
- Bootstrap/Gemfile.lock
- Bootstrap/Podfile
- Bootstrap/Podfile.lock
- Nimble-Snapshots.podspec
- README.md
Already [pushed](https://twitter.com/CocoaPodsFeed/status/559035908578476032), but this updates things on the master branch. 
Fixes #19.
Fixes #12.
> @orta => CocoaPods Trunk & CI

- Bootstrap/Bootstrap.xcodeproj/project.pbxproj
- Bootstrap/Podfile.lock
- HaveValidSnapshot.swift
- Nimble-Snapshots.podspec
> Update for Swift 2.0 and Xcode 7

- Bootstrap/Podfile.lock
- CHANGELOG
- HaveValidSnapshot.swift
> Fixes for empty snapshot problems

- README.md
I could not stop myself from removing this semicolon...
> Remove that semicolon

- HaveValidSnapshot.swift
> Merges #77.

- .travis.yml
- Gemfile
- Gemfile.lock
- Rakefile
> Run pod lib lint on CI

- Rakefile
> Add Carthage task on CI

- .swiftlint.yml
- .travis.yml
- Bootstrap/Bootstrap.xcodeproj/project.pbxproj
- Bootstrap/Bootstrap/AppDelegate.swift
- Bootstrap/Bootstrap/DynamicTypeView.swift
- Bootstrap/Bootstrap/ViewController.swift
- Bootstrap/BootstrapTests/.swiftlint.yml
- Bootstrap/BootstrapTests/ACustomFolder/BootstrapCustomFolderTests.swift
- Bootstrap/BootstrapTests/BootstrapTests.swift
- Bootstrap/BootstrapTests/DynamicSizeTests.swift
- Bootstrap/BootstrapTests/DynamicTypeTests.swift
- Bootstrap/BootstrapTests/WithoutQuickTests.swift
- DynamicSize/DynamicSizeSnapshot.swift
- DynamicType/HaveValidDynamicTypeSnapshot.swift
- DynamicType/PrettyDynamicTypeSyntax.swift
- HaveValidSnapshot.swift
- PrettySyntax.swift
- Rakefile
> SwiftLint integration

- CHANGELOG.md
- HaveValidSnapshot.swift
> Exposes public class and function.

- Bootstrap/Podfile
- Bootstrap/Podfile.lock
- CHANGELOG.md
- Cartfile
- Cartfile.resolved
- DynamicSize/DynamicSizeSnapshot.swift
- DynamicType/HaveValidDynamicTypeSnapshot.swift
- HaveValidSnapshot.swift
- Nimble-Snapshots.podspec
- Rakefile
> Fixes CI, Merges #96.

- Nimble_Snapshots.xcodeproj/project.pbxproj
Fix https://github.com/ashfurrow/Nimble-Snapshots/pull/93#issuecomment-301403640
> Fix support to XCTest when using Carthage

- Bootstrap/Podfile.lock
- CHANGELOG.md
- DynamicType/HaveValidDynamicTypeSnapshot.swift
- DynamicType/NBSMockedApplication.h
- DynamicType/NBSMockedApplication.m
- Nimble-Snapshots.podspec
This will allow us to merge all subspecs into the main one
> Remove OCMock dependency

- Bootstrap/Podfile
- Bootstrap/Podfile.lock
- CHANGELOG.md
- Nimble-Snapshots.podspec
- Nimble_Snapshots.xcodeproj/project.pbxproj
- README.md
This also enables using them with Carthage.
Fixes #89, #90
> Include all subspecs by default

- Nimble_Snapshots.xcodeproj/project.pbxproj
- Nimble_Snapshots/Nimble_Snapshots.xcconfig
Using an XCConfig file to manage multiple slices
Addresses #122
> Support Carthage tvOS

- Cartfile
- Cartfile.resolved
- CurrentTestCaseTracker.swift
Starting a new branch with Xcode 9 beta fixes.
Happy to merge into a different branch, other than `master`, but I wanted to open the PR and start the discussion first.
If somebody with push access can create a branch (suggesting `xcode9-beta` because Nimble uses the same name) I can change base for to it.
> Xcode9 beta

- .travis.yml
- Dangerfile
- Gemfile
- Gemfile.lock
https://github.com/ashfurrow/danger-swiftlint
> Moves SwiftLint to Danger plugin.

- .travis.yml
- Cartfile
- Cartfile.resolved
- CurrentTestCaseTracker.swift
- DynamicType/HaveValidDynamicTypeSnapshot.swift
This pr contains minor changes, that make the `master` branch build correctly in Xcode 9 beta 6. I have just made a global function public and removed an optional check that is no longer needed.
I tried the `xcode-beta` branch first, but it did not work in Xcode 9 beta 6.
> Xcode 9 beta 6 and Swift4 changes

- CHANGELOG.md
- Cartfile
- Cartfile.resolved
- README.md
Hi guys,
This is a small pull request with an update to the `README` and for the version of the ios-snapshot-test-case library in the `Cartfile`.
> ios-snapshot-test-case version

- README.md
#trivial
For the "pretty" syntax, updates to use correct syntax.
> Update DynamicSizeSnapshot documentation

- CHANGELOG.md
- HaveValidSnapshot.swift
This PR adds attachments to snapshot test results per #139
> Add XCAttachments to snapshot test results

- CHANGELOG.md
- HaveValidSnapshot.swift
See https://github.com/uber/ios-snapshot-test-case/issues/51 for more context
> Fix failed snapshots not being saved

- Nimble-Snapshots.podspec
- Nimble_Snapshots.xcodeproj/project.pbxproj
- Nimble_Snapshots.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Nimble_Snapshots/Nimble_Snapshots.h
This import is throwing an error on my project after updating to Nimble-Snapshots `v7.1.0`, this change looks like fixes it.
I've also added the `swift_version` to the `.podspec`
- Xcode 10.2.1
- CocoaPods 1.6.2
- macOS 10.14.5
> Fix import

- Nimble_Snapshots.xcodeproj/project.pbxproj
- Nimble_Snapshots/DynamicSize/DynamicSizeSnapshot.swift
- Nimble_Snapshots/HaveValidSnapshot.swift
as provided by iOSSnapshotTestCase
> add per pixel tolerance optional parameter

- Nimble_Snapshots/DynamicType/HaveValidDynamicTypeSnapshot.swift
Use `allSatisfy` instead (reduce_boolean)
> Fix warning: Reduce Boolean Violation

- Bootstrap/BootstrapTests/BootstrapTests.swift
- Bootstrap/BootstrapTests/DynamicSizeTests.swift
- Bootstrap/BootstrapTests/DynamicTypeTests.swift
- Nimble_Snapshots/DynamicSize/DynamicSizeSnapshot.swift
- Nimble_Snapshots/DynamicType/HaveValidDynamicTypeSnapshot.swift
- Nimble_Snapshots/HaveValidSnapshot.swift
Replace deprecated methods from Nimble 9.0.0
> Remove deprecated methods from Nimble

- README.md
Once this is merged, we can merge #229 🙌
> Adds SPM instructions to README

- .github/workflows/build-and-test.yml
- Cartfile
- Cartfile.resolved
- Nimble_Snapshots/Nimble_Snapshots.xcconfig
Add missing xcodebuild command to Carthage integration
> Add missing xcodebuild command to Carthage integration

- Bootstrap/BootstrapTests/ACustomFolder/BootstrapCustomFolderTests.swift
- Bootstrap/BootstrapTests/BootstrapTests.swift
- Bootstrap/BootstrapTests/DynamicSizeTests.swift
- Bootstrap/BootstrapTests/DynamicTypeTests.swift
- Nimble_Snapshots/CurrentTestCaseTracker.swift
Fix SPM not striping the class name from snapshot image name #246
> Fix SPM class name is not removed from snapshot image name #246

- Bootstrap/Podfile.lock
- Bootstrap/Pods/Local Podspecs/Nimble-Snapshots.podspec.json
- Bootstrap/Pods/Manifest.lock
- Bootstrap/Pods/Target Support Files/Nimble-Snapshots/Nimble-Snapshots-Info.plist
- CHANGELOG.md
- Nimble-Snapshots.podspec
> Bump version to 9.4.0
