- Bootstrap/Podfile.lock
- Nimble-Snapshots.podspec
#Fix #34 
Device agnostic features depend on latest versions of FBSnapshotTestCase but with `2.0.6` they broke our `FBSnapshotTestController` usage since it became private; `2.0.7` should make it public again.
> Upgraded FBSnapshotTestCase dependency

- CHANGELOG.md
- HaveValidSnapshot.swift
Fixes the failure messages, they were all prefixed by ", got" (e.g. ", got expected to record a snapshot in...")
I guess something recently changed in Nimble? `FailureMessage` breaking change?
> Fix failure message by removing the “, got” prefix

- Nimble_Snapshots.xcodeproj/project.pbxproj
Contrary to what README says, the project cannot be installed with Carthage for Swift 3 (Xcode 8.2):
```
/usr/bin/xcrun xcodebuild -project /Users/dawiddr/Documents/Workspace/office-timer/OfficeTimer/Carthage/Checkouts/Nimble-Snapshots/Nimble_Snapshots.xcodeproj -scheme Nimble_Snapshots -configuration Release -sdk iphoneos -toolchain com.apple.dt.toolchain.Swift_3_0 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
CARTHAGE = YES
CODE_SIGN_IDENTITY = 
CODE_SIGNING_REQUIRED = NO
ONLY_ACTIVE_ARCH = NO
SDKROOT = iphoneos10.2
TOOLCHAINS = com.apple.dt.toolchain.Swift_3_0
=== CLEAN TARGET Nimble_Snapshots OF PROJECT Nimble_Snapshots WITH CONFIGURATION Release ===
Check dependencies
“Use Legacy Swift Language Version” …
```
> Convert Nimble_Snapshots project to Swift 3

- HaveValidSnapshot.swift
Previously `currentExampleMetadata` was force unwrapped providing no context about why snapshots failed in scopes other than `it {}` blocks.
Fixes #76
> Changed unwrapping of currentExampleMetadata

- CHANGELOG.md
- DynamicSize/DynamicSizeSnapshot.swift
`isDeviceAgnostic` flag was implemented in the private function `performDynamicSizeSnapshotTest`, but is not public available in the two public functions for validating and recording snapshots with dynamic size.
The only documentation I found is a link to [DynamicSizeTests.swift](https://github.com/ashfurrow/Nimble-Snapshots/blob/74da09dc9957f2dcf522aec45d6ed883d643cf56/Bootstrap/BootstrapTests/DynamicSizeTests.swift) in [README](https://github.com/ashfurrow/Nimble-Snapshots/blob/master/README.md), however that file is being removed by @marcelofabri in #80, so I don't think I need to change anything else. Please correct me if I'm wrong :)
> Making device agnostic flag available for dynamic size snapshots

- Bootstrap/Podfile
- Bootstrap/Podfile.lock
- Cartfile
- Cartfile.resolved
- HaveValidSnapshot.swift
- NimbleSnapshotsConfiguration.swift
Updated the Nimble and Quick dependencies to latest version and removed compiler warning introduced with Swift 3.1
I have updated the Carthage metadata to use the current last version of Nimble and Quick and tweaked print of an optional string to make Swift 3.1 happy.
In latest version of Quick the `XCTestObservationCenter` has changed its implementation to suffice the lack of support for the `initialize()` method (which was override here). Current implementation on Quick this issue has been solved by using swizzling for which I'm not sure how to make it play nice with `Nimble-Snapshots`. Maybe @marcelofabri can have a look to workout together what might be the best solution.
> Updated dependencies: Quick (v.6.1.0) and Nimble (v.1.1.0). Swift 3.1 warning.

- CHANGELOG.md
- Cartfile
- Cartfile.resolved
- HaveValidSnapshot.swift
After try to install the library using Carthage with:
carthage bootstrap --platform iOS --toolchain com.apple.dt.toolchain.Swift_3_0
Carthage was failing with all the possible configurations (`branch`, `tag`, `commit`, etc) with the following message:
```bash
*** Checking out Nimble-Snapshots at "4.4.0"
*** xcodebuild output can be found in /var/folders/qv/yc3_zfm952d53b12jssfrkhjn409z6/T/carthage-xcodebuild.3kxun4.log
*** Skipped building Nimble-Snapshots due to the error:
Dependency "Nimble-Snapshots" has no shared framework schemes for any of the platforms: iOS
```
The strange thing is the project it have a  valid shared scheme. Afterwards I tried to validate Carthage for the project using:
carthage build --no-skip-current
And it was giving errors too. 
After change the `Cartfile` to …
> Fix Carthage installation

- .travis.yml
- Nimble_Snapshots.xcodeproj/project.pbxproj
- Nimble_Snapshots/Nimble_Snapshots.h
- Rakefile
Apparently, #106 broke importing with Carthage, which `rake carthage` didn't get because of caching 😬
> Fix building with Carthage

- README.md
Pull the most recent version of Nimble-Snapshot.  Old `README.md` defaulted to broken `5.1.0` version
> Updated README.md: Carthage Cartfile Update

- Nimble-Snapshots.podspec
I added the deployment target tvOs (minimum 9.0) to the `podspec` file. I thought there was more work do do, but this seems to do the trick perfectly.
In my current tvOS application I integrated this PR and it works great without having to change a line of code.
Hope this gets merged into the original repo. 🤞
> Add the tvOS deployment target to the podspec.

- Cartfile
See https://github.com/ashfurrow/Nimble-Snapshots/issues/75#issuecomment-312726545.
The lack of a version requirement can lead to a compilation error if clients have an incompatible version of `Nimble`. With this change it will result in `Carthage` failing to resolve dependency versions.
This also matches [the version required for `CocoaPods`](https://github.com/ashfurrow/Nimble-Snapshots/blob/2dc8878568c1e5207c938bf1e154a30a93de757c/Nimble-Snapshots.podspec#L22).
> Explicitly requiring Nimble ~> 7.0

- CurrentTestCaseTracker.swift
Would be nice to keep support for Xcode 8 at least until Xcode 9 is officially released. 
In our team the developers use Xcode 9 beta, but our CI is still on Xcode 8.
> Xcode 9 Beta - Keep support for Xcode 8

- CHANGELOG.md
- DynamicSize/DynamicSizeSnapshot.swift
https://github.com/ashfurrow/Nimble-Snapshots/issues/145
Consensus is that this was a typo.
> Issue #145 fixed check to use both height and width instead of just width

- CHANGELOG.md
- HaveValidSnapshot.swift
images created in attachment of test report they all have same name. reason string can be added to be more readable in reports !
> image names as attachments

- CHANGELOG.md
- HaveValidSnapshot.swift
This PR makes it possible to define reference directory path by setting the value of `FB_REFERENCE_IMAGE_DIR` environment variable.
> Reference directory path as environment variable

- .circleci/config.yml
- CHANGELOG.md
- Gemfile
- Rakefile
@ashfurrow I was following the discussion in #163 with @freak4pc about the tests failing in the CI and I worked with `second_curtain` (thanks for it 👏) in CircleCI for a while with excellent results so far ! So I decided to create this PR to add it to the project in case of we have failing test. 
Ash I think I can leave the part of add the ENV variables for the bucket in AWS to you 😅 as I don't have any clue which one we would like to use for the project 😀.
The PR can be resumed in the following:
* Include the logs for xcodebuild to use it with second_curtain.
* Run second_curtain only when some step fails to check for failed snapshot tests.
* Remove the unnecessary fastlane output directory ENV variable from the config file.
* Create a dir in the CI to store the results from xcodebuild …
> Add second_curtain to the project

- .circleci/config.yml
- CHANGELOG.md
We had `second_curtain` previously running with the output of `xcodebuild` separately and only if the build fails, the problem is the `when: on_fails` runs if some builds fail both `on_fails` will run causing the build for Swift 4.2 never being created 😅.
Also for some reason we lost the change I made before causing the cache wasn’t saved after `bundle install`.
> Run second_curtain in the pipeline of xcodebuild directly

- CHANGELOG.md
- HaveValidSnapshot.swift
Resolves #169
Favor `IMAGE_DIFF_DIR` environment variable over temporary directory for image diffs, so that user can specify a diff directory.
If no environment variable is set `IMAGE_DIFF_DIR`, use `NSTemporaryDirectory()`
> Use IMAGE_DIFF_DIR environment

- .swiftlint.yml
- Bootstrap/Bootstrap/AppDelegate.swift
- Bootstrap/Bootstrap/DynamicTypeView.swift
- Bootstrap/BootstrapTests/.swiftlint.yml
- Bootstrap/BootstrapTests/DynamicSizeTests.swift
- CurrentTestCaseTracker.swift
- DynamicSize/DynamicSizeSnapshot.swift
- DynamicType/HaveValidDynamicTypeSnapshot.swift
- DynamicType/PrettyDynamicTypeSyntax.swift
- HaveValidSnapshot.swift
This PR enable lots of opt-in rules and fixes them too.
**Rules fixed:**
- **Modifier Order Violation:** override modifier should be before public. (modifier_order)
- **Vertical Parameter Alignment On Call Violation:** Function parameters should be aligned vertically if they're in multiple lines in a method call. (vertical_parameter_alignment_on_call)
- **Unavailable Function Violation:** Unimplemented functions should be marked as unavailable. (unavailable_function)
- **Attributes Violation:** Attributes should be on their own lines in functions and types, but on the same line as variables and imports. (attributes)
- **Multiline Parameters Violation:** Functions and methods parameters should be either on the same line, or one per line. (multiline_parameters)
- **Unneeded Parentheses in …
> Enable more SwiftLint opt-in rules #trivial

- Nimble_Snapshots/DynamicSize/DynamicSizeSnapshot.swift
- Nimble_Snapshots/DynamicType/HaveValidDynamicTypeSnapshot.swift
- Nimble_Snapshots/HaveValidSnapshot.swift
The original PR added the pixel tolerance parameter to only `haveValidSnapshot`. This adds it to all of the `haveValid` functions.
The PR also added `pixelTolerance` to `FBSnapshotTest`, but as far as I could see, there was no public API to set this value. I've added `setNimblePixelTolerance` to match the other tolerance setter.
> Improve pixel tolerance support

- Nimble_Snapshots.xcodeproj/project.pbxproj
When trying to build Nimble-Snapshots for tvOS using Carthage today, the following build errors occur:
```
error: Building for tvOS Simulator, but the linked framework 'FBSnapshotTestCase.framework' was built for iOS + iOS Simulator. (in target 'Nimble_Snapshots' from project 'Nimble_Snapshots')
error: Building for tvOS Simulator, but the linked framework 'Nimble.framework' was built for iOS + iOS Simulator. (in target 'Nimble_Snapshots' from project 'Nimble_Snapshots')
```
This PR fixes the issue by removing the frameworks from the Link Binary With Libraries build phase. I borrowed this approach from [Moya](https://github.com/Moya/Moya).
> Fix issue where Nimble-Snapshots does not compile for tvOS using Carthage

- Nimble-Snapshots.podspec
This fixes https://github.com/ashfurrow/Nimble-Snapshots/issues/202 so that this gem can work with Xcode 12.
> Make Nimble-Snapshots work with Nimble 9.0 and newer

- Nimble_Snapshots/CurrentTestCaseTracker.swift
- Nimble_Snapshots/XCTestObservationCenter+CurrentTestCaseTracker.m
Hi!
We're getting this compiler error, where there is a conflict in naming for the shared instance of CurrentTestCaseTracker.
Not sure if I can get around it in some other way, but this solves it for us.
/.../Build/Products/Debug-iphonesimulator/Nimble/Nimble.framework/Headers/Nimble-Swift.h:230:103: 'CurrentTestCaseTracker' has different definitions in different modules; first difference is definition in module 'Nimble.Swift' found property name 'sharedInstance'
/.../Build/Products/Debug-iphonesimulator/Nimble-Snapshots/Nimble_Snapshots.framework/Headers/Nimble_Snapshots-Swift.h:216:103: But in 'Nimble_Snapshots.Swift' found property name 'shared'
> fix conflict with nimble bridging header

- Nimble_Snapshots/PrettySyntax.swift
Hi!
This MR adds an identifier parameter to pretty syntax for `Snapshot`
I use this feature a lot and felt it was missing.
> Add identifier to Snapshot

- Nimble-Snapshots.podspec
This is necessary because the dependency doesn't compile anymore.
.../Pods/Nimble-Snapshots/Nimble_Snapshots/HaveValidSnapshot.swift:1:8: Compiling for tvOS 9.0, but module 'FBSnapshotTestCase' has a minimum deployment target of tvOS 10.0: ...-bwcvxbxvnwfwrqdcekdprthjvvbq/Build/Products/Testing-appletvsimulator/iOSSnapshotTestCase/FBSnapshotTestCase.framework/Modules/FBSnapshotTestCase.swiftmodule/x86_64-apple-tvos-simulator.swiftmodule
> Update the tvOS version from 9.0 to 10.0

- Nimble_Snapshots/DynamicSize/DynamicSizeSnapshot.swift
- Nimble_Snapshots/HaveValidSnapshot.swift
According to this issue [#223 ](https://github.com/ashfurrow/Nimble-Snapshots/issues/223)
> Compare snap shot ignore screen scale 

- CHANGELOG.md
- Package.swift
Hi @ashfurrow could you please test this PR ? My MacBook is too old to run Big Sur (MacBook 2013), so I'm stuck with Catalina and Xcode 12.3
> Add Swift Package Manager support

- Package.swift
Downgrade swift-tools package to 5.3, allowing older versions of Xcode to use SPM
> Add swift-tools 5.3 package

- .github/workflows/build-and-test.yml
Ran into a problem in #255 where the Danger run prevented tests from being ran at all. This PR moves Danger to the end, which will be faster than trying to get all the tests running locally for me at the moment 😅
> Moves Danger to end of CI run

- Package.resolved
- Package.swift
The update to Nimble 11 something had broking in the Package configuration, I fixed it and also update to new syntax to avoid deprecation warnings.
> Fix Swift Package definition

- Nimble-Snapshots.podspec
Fixes https://github.com/ashfurrow/Nimble-Snapshots/issues/258
> - Fixes https://github.com/ashfurrow/Nimble-Snapshots/issues/258

- CHANGELOG.md
- Cartfile.resolved
- Nimble-Snapshots.podspec
- Nimble_Snapshots/DynamicSize/DynamicSizeSnapshot.swift
- Nimble_Snapshots/DynamicType/HaveValidDynamicTypeSnapshot.swift
- Nimble_Snapshots/HaveValidSnapshot.swift
- Package.resolved
- Package.swift
- Bumped Nimble version to 13.2.0
- Refactored code to not use deprecated Nimble types
> Support Nimble 13.0.0
